spring.application.name=moodify-backend
server.port=8081

spring.jackson.serialization.indent-output=true

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:./target/moodifydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 🔐 AUTH0 / JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-5l3w1yvav5vmutet.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://moodify-api